---

version: '2'
services:

    database:
        image: mongo:latest
        container_name: mongodb
        expose:
            - 27017
        ports:
            - 27017:27017
        env_file:
            - docker_build/env/dev

    webserver:
        image: ilumi_dev
        build:
            context: .
            dockerfile: ./docker_build/application/Dockerfile
        container_name: webserver
        restart: always
        links:
            - database
        ports:
            - 80:5000
        volumes:
            - .:/usr/src/app/
        env_file:
            - docker_build/env/dev
